
ALTER TABLE public.audit
  ADD COLUMN IF NOT EXISTS ai_status TEXT NOT NULL DEFAULT 'idle',
  ADD COLUMN IF NOT EXISTS ai_score INTEGER,
  ADD COLUMN IF NOT EXISTS ai_grade TEXT,
  ADD COLUMN IF NOT EXISTS ai_details JSONB,
  ADD COLUMN IF NOT EXISTS ai_last_error TEXT,
  ADD COLUMN IF NOT EXISTS ai_fetched_at TIMESTAMPTZ;
